### PR TITLE
Modified main interface

### PR DESCRIPTION
**Pull request by MclTTI**
Added config.yml file.
Modified ERA5_retrieve_postproc.py accordingly.

### CODE REVIEW

**Comment by oloapinivad** [comment]
Very nice idea, I was thinking of something like this, see #4. Perhaps we can port the parsers too? 

https://github.com/oloapinivad/CDS-retriever/blob/parsing/ERA5_retrieve_postproc.py

**Comment by MclTTI** [comment]
Sure thing!
There is a small correction to be made in my config file, then I can simply use your parser,
In this way, an user only has to modify the config file, without touching the scripts.

**Comment by MclTTI** [comment]
Parser complete with your options!
I’ve created a new config.py file and moved the configuration code for the main script there.

**Comment by oloapinivad** [comment]
What's the status of this one? I assume I can close #4 now

**Comment by oloapinivad** [comment]
What's up? Change of plan?

**Comment by MclTTI** [comment]
Yes, just for order...
This was my main dev branch, I'm setting up a new thematic branch with only the stuff related to this pull request

**Pull request closed without merging**
